[project]
name = "freelance"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.main]
path = "contracts/main.clar"

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"

[contracts.vibes-token]
path = "contracts/vibes-token.clar"
depends_on = ["sip-010-trait"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
